// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkcLsJLapctxfaR1wRvjLDAg_lOrR4e_8',
    appId: '1:886146051971:web:bd4b5a2db1cbaa6a9150b6',
    messagingSenderId: '886146051971',
    projectId: 'fir-flutter-codelab-58c04',
    authDomain: 'fir-flutter-codelab-58c04.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-58c04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVN4wm7Ya9kJaZPtMtwehNWV64vwBQ15E',
    appId: '1:886146051971:android:a879481217fedef89150b6',
    messagingSenderId: '886146051971',
    projectId: 'fir-flutter-codelab-58c04',
    storageBucket: 'fir-flutter-codelab-58c04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTrYcJKERNFnpEV3_G2Vod4TZet_Tc2UM',
    appId: '1:886146051971:ios:091cffd862af65749150b6',
    messagingSenderId: '886146051971',
    projectId: 'fir-flutter-codelab-58c04',
    storageBucket: 'fir-flutter-codelab-58c04.appspot.com',
    iosClientId: '886146051971-qfbn1lqjimcdn0uv5kmmeclqct9e1s7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTrYcJKERNFnpEV3_G2Vod4TZet_Tc2UM',
    appId: '1:886146051971:ios:091cffd862af65749150b6',
    messagingSenderId: '886146051971',
    projectId: 'fir-flutter-codelab-58c04',
    storageBucket: 'fir-flutter-codelab-58c04.appspot.com',
    iosClientId: '886146051971-qfbn1lqjimcdn0uv5kmmeclqct9e1s7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
